In [1]:
#pandas is a libray it contains functions related to the database
import pandas as pd

In [2]:
#Now we are going to load dataset
#dataset is called by pd.read_csv function under pandas and assigned to the dataset varaiable.
dataset=pd.read_csv("Salary_Data.csv") 
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
#Data was already preprocessed. Now we are going to perform Input and output variables split
independent=dataset[["YearsExperience"]] 
independent #Now 'YearsExperience' column value seperately assigned into independent varaiable, Independent means input, Dependent means output.

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [4]:
#Now 'Salary' column value seperately assigned into dependent varaiable, dependent means output.
dependent=dataset[["Salary"]] #Now Salary value seperately assigned into dependent varaiable,
dependent
#Now we got seperatley independent and dependent varaiables. now sucessfully splited input and output

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [5]:
#Split Trainset and Testset. 
#Using sklearn library going to split Trainset and Testset. it's supporting for Machine Learning.
#respective folder(skleran) under this function(model_selection) we are going to (import) or calling train_test_split
#Not calling all functions under this respective folder(skleran) under this function(model_selection) we are going to call train_test_split.
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0) #No varaiable assigned here.here parallely split input and output based on 70:30 ratio.
#we are using _(underscore) instead of space into vraiables(X_train,X_test,y_train,y_test)
#X means input, y means output, X input based on trainset and testset(X_train,X_test) and also y was output based trainset and testset(y_train,y_test) 
#if you want to use sklearn library based on trainset and testset you have to split it like this four variables(X_train,X_test,y_train,y_test).
#As of now compltetd Trainset and Testset split.

In [6]:
#Model Creation
#ML algorithm all are provided by sklearn 
from sklearn.linear_model import LinearRegression # While calling, this line loaded into memory. here LinearRegression may be function or class. In this line LinearRegression considered as class
regressor=LinearRegression() #Non parameterized function we are assigning into regressor varaiable.it consider as class, all the function under this class assign to regressor.
regressor.fit(X_train,y_train) #fit function we are calling it using access operator, now passing splited trainset input and output.
#here just calling sklearn folder under linear_model we are calling LinearRegression function only. due to this kind of calling memory consumption will be low
#what are all the functions LinearRegression under this class loaded into regressor varaable.
#class and functions are just we can call it as procedure.
#First two lines are procedure.we have holded weight and bias values, while calling fit() after execution this line it'll calculate weight and bias.now Model is ready.
#Third line when we call fit method and passing materials(X_train,y_train). this formula respective place substitute values. For this particular block have Learning phase going to happen here,

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
#Now we have to see Module calculated value.
weight=regressor.coef_  #coef_ method using to calculate weight. while calling this "regressor.coef_" it will save it into weight varaiable 
weight #checking weight saved value. weight/slope is next prediction hook. we should know how pattern going.

array([[9360.26128619]])

In [8]:
bais=regressor.intercept_  #intercept_ method using to calculate bais. while calling this "regressor.intercept" it will save it into bais varaiable 
bais #checking bais saved value.
#regressor.fit(X_train,y_train) -In this regressor all are saved(formula,weight,bais)
#Now we know weight and bais

array([26777.3913412])

In [10]:
#Evaluation metrix(R2 using)
y_pred=regressor.predict(X_test) #y-pred is varaiable, all are saved in regressor(formula,weight,bais), predict is application function.
#Evaluation matrix should happened on Testdataset .Anyone of the Testset values not included into Trandataset values. so that we are using it for crosss predition
#y-test is Actual data(y_test), X_test is brain predicted outptut.so that we are using it for crosss prediction

In [11]:
from sklearn.metrics import r2_score #using this r2_score function going to find R2 value.
r_score=r2_score(y_test,y_pred) #r2_score assigned to r_score variable, now passing Actual output(y_test) and predicted output(y_pred)
#regressor=LinearRegression()
#r2_score result nearly 1 means it's Good model, nearly to 0 means bad model
#Now it nearly to 1. our model is performing well. our model learned well while performing crosscheck. evaluation matrix cross checking our model and it'll confirm particular model is performing well or not.

In [12]:
r_score

0.9740993407213511

In [13]:
#To save model we are using pickle function.
import pickle
filename="finalized_model_linear.sav" #creating dummy filename for finalized model. to save pickle file we have to use .sav
#now it was created filename, not yet included into model

In [15]:
pickle.dump(regressor,open(filename, 'wb')) #This file will be saved same like document file which we are all available into below place
#D:\AI\Week3-Machine Learning-Regression Handson\Machine Learning-Regression\1.Simple Linear Regression
#wb - write binary, rb -read.
#Now Model saved, so once load and check it, it's working fine or not. if everything fine means we will move this model to Deployment phase, end user application use related we can set it.

In [16]:
#Now Model saved, so once load and check it, it's working fine or not. if everything fine we will move this model to phase2 ,Deployment, end user application use related we can set it.
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb')) #creating varaiale name loaded_model, if I want to use saved Model and want to load again means use "pickle.load(open("finalized_model_linear.sav",'rb'" and here only reading so used rb.
#Always use extension properly to load model
result=loaded_model.predict([[13]])
#once loading completed means we are going test it real time based on single user. now we are predicting salary for 15 years of experience. Individual value sending time use two closed brackets like this([[15]]).
#predict([[15]]) here we can forward python int varaiable value as input. Now saved model loaded and predicting result.

In [17]:
result

array([[148460.78806172]])

In [19]:
#Now we are going to start Phase2, phase 2 seperately check with one file.end user application team is preparting send to this brain to that team. As a AI enginner create one good brain and test and send to concern team.
import pickle  #we need this file required

In [20]:
#Now Model saved, so once load and check it, it's working fine or not. if everything fine we will move this model to phase2 ,Deployment, end user application use related we can set it.
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb')) #creating varaiale name loaded_model, if I want to use saved Model and want to load again means use "pickle.load(open("finalized_model_linear.sav",'rb'" and here only reading so used rb.
#Always use extension .sav properly to load model
result=loaded_model.predict([[16]])
#once loading completed means we are going test it real time based on single user. now we are predicting salary for 16 years of experience. Individual value sending time use two closed brackets like this([[16]]).
#predict([[16]]) here we can forward python int varaiable value as input. Now saved model loaded and predicting result.

In [21]:
result

array([[176541.5719203]])

In [ ]:
#we got above final result. In our dataset "yearsof experience" value starts from 1.1, if we want to know less than 1 year experience person salary means, pass value like below
#26777.3913412 is bias value, origin intecept value
#y=mx+c, y=9360+26777(it's bais value,origin,minimum value)
#incase if your years of experience 0 means y=9360[0]+26777=0+26777=26777, if you want to know origin/intial value means bais will give that result. here "0" years of experience person result given by bais value that is called origin.